[package]
name = "devsm"
version = "0.1.0"
edition = "2024"

[profile.release]
#lto = "thin"
debug = true

[profile.profiling]
inherits = "release"
debug = true

# [profile.dev]
# debug = 0

[dependencies]
anyhow = "1.0.100"
kvlog = "0.1.3"
libc = "0.2.177"
mio = { version = "1.0.4", features = [
    "os-poll",
    "os-ext",
], default-features = false }
slab = "0.4.11"
unicode-segmentation = "1.12.0"
unicode-width = { version = "0.2.2", default-features = false }
vtui.path = "../../vtui"
jsony = "0.1.8"
bumpalo = { version = "3.19.0", features = ["collections"] }
memchr = "2.7.6"
sendfd = "0.4.4"
jsony_value.path = "../../tests/jsony_value"

[dev-dependencies]
#proptest = "1.9.0"
vt100 = "*"
