[package]
name = "dfj"
version = "0.1.0"
edition = "2024"

[profile.release]
lto = "fat"

[dependencies]
anyhow = "1.0.100"
kvlog = "0.1.3"
libc = "0.2.177"

mio = { version = "1.0.4", features = [
    "os-poll",
    "os-ext",
], default-features = false }
mio-pidfd = "0.4.0"
slab = "0.4.11"
unicode-segmentation = "1.12.0"
unicode-width = { version = "0.2.2", default-features = false }
vtui.path = "/home/user/Projects/vtui"
vt100 = "*"
jsony = "0.1.8"
compact_str = "0.9.0"
bumpalo = { version = "3.19.0", features = ["collections"] }
memchr = "2.7.6"
jsony_bench.path = "/home/user/Projects/git/jsony/jsony_bench"
