[package]
name = "devsm-rpc"
version = "0.1.0"
edition = "2024"

[dependencies]
jsony = "0.1.8"
jsony_value.path = "../../../tests/jsony_value"

[dev-dependencies]
anyhow = "1.0"
jsony = "0.1.8"

[[example]]
name = "subscribe"
path = "examples/subscribe.rs"
